export { default as AddIcon } from "./add";
export { default as DnDIcon } from "./dnd";
export { default as DeleteIcon } from "./delete";
export { default as ExitIcon } from "./exit"
export { default as SettingIcon } from "./settings";
export { default as HumansIcon } from "./humans";
export { default as MarketingIcon } from "./marketing";
export { default as SalesIcon } from "./sales";
export { default as AccountIcon } from "./account";
export { default as AcademyIcon } from "./academy";
export { default as Logo } from "./logo";
export { default as UserIcon } from "./user";
export { default as BackIcon } from "./backicon";
export { default as Chevrodown } from "./chevrodown";
export { default as SearchIcon } from "./search";
export { default as PlusIcon } from "./plus";
export { default as OverIcon } from "./over";
export { default as SquareIcon } from "./square";
